### PR TITLE
fixed detection of binary strings (#132)

### LINKED ISSUE #132: Binary string detection is broken (introduced with 1.9.0)
**PHP version**: all versions

**Description**
With #126 and #128 a change was introduced that is supposed to prevent binary messages from being dumped. In [FullHttpMessageFormatter](https://github.com/php-http/message/blob/master/src/Formatter/FullHttpMessageFormatter.php#L89) line 89 the following code is used to detect binary strings:

```php
        if (preg_match('/([\x00-\x1F\x7F])/', $data)) {
            return $message.'[binary stream omitted]';
        }
```

Unfortunatly, this regex includes common whitespaces like \t, \r and \n as well. In consequence, all output is hidden and replaced with `[binary stream omitted]`, even if the document is a simple HTML or XML document. I doubt that this is the intentioned behaviour, since linebreaks a by far an indicator for a binary string and moreover very common in HTML or XML documents.

**Possible Solution**
The code could be changed as follows, see https://stackoverflow.com/questions/25343508/detect-if-string-is-binary:

```php
        if (preg_match('~[^\x20-\x7E\t\r\n]~', $data)) {
            return $message.'[binary stream omitted]';
        }
```

However, this would still be problematic regarding non-English languages, i.e. special characters in French, Spanish, Italian or German would still trigger falsely the binary detection. Therefore, I would suggest to check for all non-prinable ASCII characters as well as \<del> (\x7F) and explicitly exclude \<cr> (\x0D), \<lf> (\x0A) and \<tab> (\x0B).

```php
        // all non-printable ASCII characters and <DEL> except for \t, \r, \n
        if (preg_match('/([\x00-\x09\x0C\x0E-\x1F\x7F])/', $data)) {
            return $message.'[binary stream omitted]';
        }
```

The same change should probably be applied to [CurlCommandFormatter](https://github.com/php-http/message/blob/master/src/Formatter/CurlCommandFormatter.php) as well.

What do you think?

### PR DESCRIPTION
**Pull request by driehle**
| Q               | A
| --------------- | ---
| Bug fix?         | yes
| New feature?    | no
| BC breaks?      | no
| Deprecations?   | no
| Related tickets | fixes #132
| License         | MIT

See #132, tests have been added.

### CODE REVIEW

File: src/Formatter/CurlCommandFormatter.php [hunk 1]
```diff
@@ -42,9 +42,12 @@ public function formatRequest(RequestInterface $request)
             } elseif ($body->isSeekable()) {
                 $data = $body->__toString();
                 $body->rewind();
-                if (preg_match('/[\x00-\x1F\x7F]/', $data)) {
+                // all non-printable ASCII characters and <DEL> except for \t, \r, \n
+                if (preg_match('/([\x00-\x09\x0C\x0E-\x1F\x7F])/', $data)) {
                     $data = '[binary stream omitted]';
                 }
+                // replace \t, \r and \n with their string literals
+                $data = str_replace(["\t", "\r", "\n"], ['\t', '\r', '\n'], $data);
```
Comment (dbu) [inline src/Formatter/CurlCommandFormatter.php:50]: if i copy-paste this onto a console, does the `\t` / `\r` / `\n` work correctly? i am a bit afraid of cluttering the content with such characters - but when we output as html, the newlines would get lost, so this might be the right solution.

Comment (driehle) [reply src/Formatter/CurlCommandFormatter.php:50]: Good catch, it will not work due to the `escapeshellarg()` later on. We could simple not care about these three characters at all and `escapeshelarg()` will do the rest. The output will then look somehow like this:

```
curl --......  --data 'foo
bar' http://foo/bar
```

This doesn't look nice, but it can be copy and pasted.

Comment (dbu) [reply src/Formatter/CurlCommandFormatter.php]: i prefer less nice but working :-D

File: spec/Formatter/CurlCommandFormatterSpec.php [hunk 2]
```diff
@@ -91,6 +91,24 @@ function it_formats_requests_with_null_bytes(RequestInterface $request, UriInter
...
+        $body->getSize()->willReturn(1);
+        $body->isSeekable()->willReturn(true);
+        $body->rewind()->willReturn(true);
+
+        $uri->withFragment('')->willReturn('http://foo.com/bar');
+        $request->getMethod()->willReturn('POST');
+        $request->getProtocolVersion()->willReturn('1.1');
+        $request->getHeaders()->willReturn([]);
+
+        $this->formatRequest($request)->shouldReturn("curl 'http://foo.com/bar' --request POST --data 'foo\\nbar'");
```
Comment (dbu) [inline spec/Formatter/CurlCommandFormatterSpec.php:109]:
```suggestion
        $this->formatRequest($request)->shouldReturn("curl 'http://foo.com/bar' --request POST --data 'foo\nbar'");
```

**Comment by dbu** [comment]
thanks a lot, i will tag a release
