### PR TITLE
Fix fatal error for long bodies

### LINKED ISSUE #93: CurlFormatter fails on large boddies
| Q            | A
| ------------ | ---
| Bug?         | yes
| New Feature? | no
| Version      | Master

#### Actual Behavior

When posting super large bodies you will get an error because escshellargs does not allow more than X chars. https://github.com/php-http/message/blob/v1.4.1/src/Formatter/CurlCommandFormatter.php#L42

We should make sure to catch/suppress that error and write a better error message in the curl string.

### PR DESCRIPTION
**Pull request by GaryPEGEOT**
| Q               | A
| --------------- | ---
| Bug fix?        | yes
| New feature?    | no
| BC breaks?      | no
| Deprecations?   | no
| Related tickets | fixes #93 
| Documentation   | 
| License         | MIT

#### What's in this PR?

Prevent `CurlCommandFormatter` to throw a Fatal exception when body size exceed `escapeshellarg` argument allowed length. Didn't find a great way to get the limit tho... Windows limit come from [PHP source code](https://github.com/php/php-src/blob/959091285487878790f2f2fe71301954f3c765a9/ext/standard/exec.c#L62-L80), the UNIX from 
```
echo $(getconf ARG_MAX)
```
If you have a better solution to find `escapeshellarg` limit, I'm all ears

#### Checklist

- [x] Updated CHANGELOG.md to describe bugfix

### CODE REVIEW

**Comment by GaryPEGEOT** [comment]
> maybe lets just limit to 8192 and say that this should work on all operating systems. wdyt?

Totally agree, it's neither user friendly nor memory friendly

File: src/Formatter/CurlCommandFormatter.php [hunk 1]
```diff
@@ -36,7 +36,10 @@ public function formatRequest(RequestInterface $request)
 
         $body = $request->getBody();
         if ($body->getSize() > 0) {
-            if ($body->isSeekable()) {
+            // escapeshellarg argument max length on Windows, but impractical to use either way
```
Comment (dbu) [inline src/Formatter/CurlCommandFormatter.php]: maybe say "... max length on Windows, but longer body in curl command would be impractical anyways."

File: src/Formatter/CurlCommandFormatter.php [hunk 2]
```diff
@@ -36,7 +36,10 @@ public function formatRequest(RequestInterface $request)
...
+            if ($body->getSize() > 8192) {
+                $data = '[too long stream omitted]';
+            } elseif ($body->isSeekable()) {
                 $data = $body->__toString();
```
Comment (dbu) [inline src/Formatter/CurlCommandFormatter.php]: could we have a body that does not know its size? then we might need to check again how long $data is?

Comment (GaryPEGEOT) [reply src/Formatter/CurlCommandFormatter.php]: on line 38 your have 
```php
if ($body->getSize() > 0) {
```

So I guess passing that point, it knows it size. But I can add another check just in case

File: src/Formatter/CurlCommandFormatter.php (hunk 1 above)
Comment (GaryPEGEOT) [reply src/Formatter/CurlCommandFormatter.php]: Updated :)

File: src/Formatter/CurlCommandFormatter.php (hunk 2 above)
Comment (dbu) [reply src/Formatter/CurlCommandFormatter.php]: oh, i missed that. no then its fine!

**Comment by dbu** [comment]
thanks!

**Comment by dbu** [comment]
released 1.8.0 with this and some other fixes.
